### ISSUE TITLE
Add commands to switch the source

### ISSUE THREAD

**Issue by tlindener** [ttu/node-yamaha-avr#1]
Hi, first of all thanks for your great work! I'm new to nodejs but I'm incredibly excited to finally be able to configure my avr!

The only thing I'm missing is the ability to change the source (HDMI, AV) are you planning to implement this feature as well?

**Comment by ttu** [comment]
Hi. This project was only a test project so I could try to add new device to The Thing System home automation. Therefore this has a very limited functionality, but I'm glad that you have found some use for this.

I added the functionality you were hoping this would have, but I would recommend that you would check e.g. https://github.com/PSeitz/yamaha-nodejs as it has more functionality already implemented.

Br,
Tomi
