### ISSUE TITLE
Volume command has no effect (Yamaha RX-V477)

### ISSUE THREAD

**Issue by tjanson** [ttu/node-yamaha-avr#2]
Hi!

Thanks for your work on this, it’s pretty cool. All commands work with one exception: Changing the volume.

First, any volume value triggers "is not a number", but this can easily be fixed by adding `parseInt`.

Now the real issue: No matter what value I choose, the volume of the AVR does not change.
I see you wrote the value should be above `200`. [This Yamaha document (“RX AX10 VX71 Series Function Tree.xls”)](http://www.avhifiresources.co.uk/content/Dealer%20News-Info/Custom%20Installer%20Info/RX%20AX10%20VX71%20Series%20Function%20Tree.xls) specifies the range as `9-203` corresponding to [–80.5 dB, 16.5 dB] in 0.5 dB steps (but I suppose the API could have changed for the VX77 series).
For comparison, the status output (in full [here](https://gist.github.com/tjanson/424cf8187ef519299b9b)) contains `"Volume":[{"Lvl":[{"Val":["-575"],"Exp":["1"],"Unit":["dB"]}]` when the AVR is set to –57.5 dB.

I tried any value I could think of from -1000 to 1000 (I removed the ≥  200 "safety" for this), no luck. Any idea? What range do you use for volume on your AVR?

Cheers,
TJ

**Comment by tjanson** [comment]
Yay, I figured it out: It was as simple as `db` needing to be `dB` (sic!). Just for the record, the changes are in #3. This works with my V477. I’ll close both this issue and the PR – just wanted to publish it in case someone else comes across this.

**Comment by ttu** [comment]
I could swear that this used to work. Tried again and didn't work, so can't even use famous 'works on my machine' excuse ;)

I should have written down which firmware version my amplifier (RX-V475, v1.26) had when I wrote this.

I reopened your pull request and merged it. Thanks for the update!

**Comment by tjanson** [comment]
No problem. I forgot to change the usage example. Fixed in #4.
